#define ONE_SECOND_MEMORY 16000
#define MILISECONDS 1000
#define MAX_VOLUM 0xFFFFFFFF
#define MONO 1
#define STEREO 2
#define FORMAT_PCM 1
#define PCM_SUBCHUNK1SIZE 16
#define DEFAULT_SAMPLE_RATE 44100
#define DEFAULT_BITS_PER_SAMPLE 16
#define BYTE 8
#define NUMBER_SYMBOLS_WAV 4	
#define STRING_NUMBER_SYMBOLS_WAV 5				// NUMBER_SYMBOLS_WAV + slot for \0
#define DEFAULT_NBLOCKALIGN 2					// Block SUBCHUNK1 and SUBCHUNK2
#define OUTPUT_LOOP 1